environment:
  matrix:
    # node.js
    # nodejs_version: "0.10"
    # nodejs_version: "0.12"
    # nodejs_version: "4"
    # nodejs_version: "6"
    # nodejs_version: "8"
    # nodejs_version: "10"
    # nodejs_version: "12"
    - nodejs_version: "14"

install:
  - npm install -g npm@^3
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off

# build version format
version: "{build}"
